language: rust
sudo: false
dist: trusty

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env:
        - BENCH=yes
        - FEATURES=jit
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
  - ([ -z "$BENCH" ] || cargo bench --verbose --features "$FEATURES")
  - ([ -z "$BENCH" ] || scripts/benchmark.sh)

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - llvm
