[package]
name = "bf"
version = "0.2.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]

[features]

# Enables native x64 JIT
jit = ["dynasmrt", "dynasm"]

# Omits memory bounds checks from emitted code
omit_bounds_checks = []

[dependencies]
clap = "2.24"

dynasmrt = { version = "*", optional = true }
dynasm = { version = "*", optional = true }
