[package]
name = "bf"
version = "0.2.2"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
description = "An optimizing Brainfuck interpreter"
repository = "https://github.com/tov/bf-rs"
homepage = "https://github.com/tov/bf-rs"
documentation = "http://tov.github.io/bf-rs/"
readme = "README.md"
license = "MIT"
keywords = ["brainfuck", "interpreters", "jit"]

[features]

# Enables native x64 JIT; requires nightly Rust
jit = ["dynasmrt", "dynasm"]

[dependencies]
clap = "2.24"

dynasmrt = { version = "*", optional = true }
dynasm = { version = "*", optional = true }
