[package]
name = "bf"
version = "0.2.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]

[features]

# Enables native x64 JIT; requires nightly Rust
jit = ["dynasmrt", "dynasm"]

# Omits memory bounds checks from emitted code; implies jit
omit_bounds_checks = ["jit"]

[dependencies]
clap = "2.24"

dynasmrt = { version = "*", optional = true }
dynasm = { version = "*", optional = true }
