[package]
name = "bf"
version = "0.2.1"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]

[features]

# Enables native x64 JIT; requires nightly Rust
jit = ["dynasmrt", "dynasm"]

[dependencies]
clap = "2.24"

dynasmrt = { version = "*", optional = true }
dynasm = { version = "*", optional = true }
